### ISSUE TITLE
Not an issue, just a noob question

### ISSUE THREAD

**Issue by mkshb** [harshdoshi999/node-url-shortener#1]
Hey there,

can you help me getting values from the funtion?
`shortUrl.short('https://google.com', function(err, url){
    console.log(url);
});`
How can i return url to use it in my scripts?

Thanks in advance.

**Comment by harshdoshi999** [comment]
Hi,
Please paste your code here. Thanks.

**Comment by mkshb** [comment]
Hey there,
i am trying to return url into surl, but it's always undefined.

> var fullurl = 'https://my.url.com';
> var surl = shortUrl.short(fullurl, function(err, url){ return url; });	
> console.log(surl);

Thanks in davance

**Comment by harshdoshi999** [comment]
Please use promise or async functionality.

**Comment by harshdoshi999** [comment]
Closing this issue as no further activity since past 7 days.

**Comment by ovesh786** [comment]
var shortUrl = require("node-url-shortener");

const fullUrl = 'https://github.com/harshdoshi999/node-url-shortener/issues/2';

const shortenUrl = (url) => {
  return new Promise((resolve, reject) => {
    shortUrl.short(url, (err, shortenedUrl) => {
      if (err) {
        reject(err);
      } else {
        resolve(shortenedUrl);
      }
    });
  });
};

(async () => {
  try {
    const surl = await shortenUrl(fullUrl);
    console.log('Shortened URL:', surl);
  } catch (err) {
    console.error('Error shortening URL:', err);
  }
})();

im uisng code like that can u please help me @harshdoshi999 why await surl  give undefined?
