### ISSUE TITLE
Can't use url outside of the function.

### ISSUE THREAD

**Issue by onurusluca** [harshdoshi999/node-url-shortener#2]
shorter() {
      shortUrl.short(this.src, function (err, url) {
      this.urlShare = url;
      });
    }
gives error:

Uncaught TypeError: Cannot set property 'urlShare' of undefined

**Comment by harshdoshi999** [comment]
That's because "this" is not defined inside the function.

`shorter() {
  this.urlShare = shortUrl.short(this.src, function (err, url) {
    return url;
  });
}`

Try this way!!

**Comment by onurusluca** [comment]
Really appreciate it! That did it.

**Comment by onurusluca** [comment]
I am very sorry but I can't still get it apparently. I still get undefined.

  shorter() {
      this.urlShare = shortUrl.short(this.src, function (err, url) {
//logging url here gives the short url 
        return url;
      });
//login this.urlShare or using it outside gives undefined
    },

**Comment by onurusluca** [comment]
I am using Vue, do you think that might have something to do with the problem?

`<template>
  <div id="image">
    <h2>Upload Successful</h2>
    <a target="_blank" :href="src">Image Link</a>
    <button @click="shorter">Short URL</button>
    <p>{{ urlShare }}DD</p>

    <div class="img">
      <a target="_blank" :href="src"> <img :src="src" alt="" /> </a>
    </div>
  </div>
</template>

<script>
var shortUrl = require("node-url-shortener");

export default {
  name: "Image",
  props: ["src"],
  data() {
    return {
      url: "",
      urlShare: null,
    };
  },

  methods: {
    shorter() {
      this.urlShare = shortUrl.short(this.src, function (err, url) {
        return url;
      });
      console.log(this.urlShare);
    },
  },
};
</script>
`

**Comment by onurusluca** [comment]
I am using Vue, do you think that might have something to do with the problem?

<template>
  <div id="image">
    <h2>Upload Successful</h2>
    <a target="_blank" :href="src">Image Link</a>
    <button @click="shorter">Short URL</button>
    <p>{{ urlShare }}DD</p>

    <div class="img">
      <a target="_blank" :href="src"> <img :src="src" alt="" /> </a>
    </div>
  </div>
</template>

<script>
var shortUrl = require("node-url-shortener");

export default {
  name: "Image",
  props: ["src"],
  data() {
    return {
      url: "",
      urlShare: null,
    };
  },

  methods: {
    shorter() {
      this.urlShare = shortUrl.short(this.src, function (err, url) {
        return url;
      });
      console.log(this.urlShare);
    },
  },
};
</script>

**Comment by onurusluca** [comment]
```
<template>
  <div id="image">
    <h2>Upload Successful</h2>
    <a target="_blank" :href="src">Image Link</a>
    <button @click="shorter">Short URL</button>
    <p>{{ urlShare }}DD</p>

    <div class="img">
      <a target="_blank" :href="src"> <img :src="src" alt="" /> </a>
    </div>
  </div>
</template>

<script>
var shortUrl = require("node-url-shortener");

export default {
  name: "Image",
  props: ["src"],
  data() {
    return {
      url: "",
      urlShare: null,
    };
  },

  methods: {
    shorter() {
      this.urlShare = shortUrl.short(this.src, function (err, url) {
        return url;
      });
      console.log(this.urlShare);
    },
  },
};
</script>

```

**Comment by onurusluca** [comment]
Got it working with this. With function I was just using a callback instead of returning a value.

shorter() {
   shortUrl.short(this.src, (err, url) => {
      this.urlShare = url;
      console.log(this.urlShare);
   });
},
