### ISSUE TITLE
Query Parameter is not allowed?

### ISSUE THREAD

**Issue by ArcherEmiya05** [harshdoshi999/node-url-shortener#3]
It seems that query params are not allowed/supported.

**Comment by harshdoshi999** [comment]
@ArcherEmiya05 what you trying to do? Please do share your proper code example.

**Comment by ArcherEmiya05** [comment]
> 
> 
> @ArcherEmiya05 what you trying to do? Please do share your proper code example.

Query in URL is not included in short link
Example link is `https://adrenture-app.web.app/getList?&idToken=eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5NmFhNzRjODFiZTYwYjI5NDg1NWE5YTVlZTliODY5OGUyYWJlYzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYWRyZW50dXJlLWFwcCIsImF1ZCI6ImFkcmVudHVyZS1hcHAiLCJhdXRoX3RpbWUiOjE2MDc5OTcyMzEsInVzZXJfaWQiOiJuMVU5cHhTa043WXBRY2Y1M1NUSXUyVmpkakgzIiwic3ViIjoibjFVOXB4U2tON1lwUWNmNTNTVEl1MlZqZGpIMyIsImlhdCI6MTYwNzk5NzIzMSwiZXhwIjoxNjA4MDAwODMxLCJlbWFpbCI6ImFkcmVudHVyZS5hZG1pbkBhZHJlbnR1cmUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFkcmVudHVyZS5hZG1pbkBhZHJlbnR1cmUuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.catw-dwjt9gIOb&collection=Users&page=1`

Only `https://adrenture-app.web.app/getList?` is return from the shortened link

**Comment by harshdoshi999** [comment]
Hi @ArcherEmiya05 , I'll look into it and release new version soon.

**Comment by JasonLeviGoodison** [comment]
Hey following up on this. Need to include a query param and getting blocked

**Comment by karthik666manjunath** [comment]
Hey. Any update on the query parameter ?

**Comment by bdodroid** [comment]
@karthik666manjunath 

I was able to get around this by encoding the url, e.g:

`shortUrl.short(encodeURIComponent("https://url.com/test?test=test&alsoTest=test"), function (err: any, url: String){
 console.log(url);
});`

**Comment by karthik666manjunath** [comment]
Let me try this. Thanks !

**Comment by harshdoshi999** [comment]
Thanks @bdodroid. Fixed this in version >=2.0.2 @karthik666manjunath
