### ISSUE TITLE
This package is not working

### ISSUE THREAD

**Issue by GitanjaliCS** [harshdoshi999/node-url-shortener#5]
Hello 
Please help me.

A simple code is not working now

var shortUrl = require("node-url-shortener");

  shortUrl.short("https://google.com", function (err, url) {
    if (err) console.log(err);
    console.log(url);
  });

I am trying from yesterday. Please help me out.

**Comment by harshdoshi999** [comment]
Hi @GitanjaliCS , please share error/output of your code.

**Comment by GitanjaliCS** [comment]
There is no error showing.

**Comment by harshdoshi999** [comment]
I'm not sure what error you're getting. And without seeing output or error, I can't help you with that. Please share your code file.

**Comment by harshdoshi999** [comment]
Please share the URL you're trying to shorten here along with exact code snippet you have in your application. It seems like code snippet you have shared is different than what I see in screenshot.

**Comment by GitanjaliCS** [comment]
const handleSMS = async (clientDetails, idAttr) => {
   
    let postData = {
      title: "Prescriptions",
    };
    await CompanyService.getSmsTemplateByTitle(postData)
      .then(async (result) => {
        let shortenUrl = "";
        await shortUrl.short(
          `${result.data.url}/pdf/client_prescription_pdf/${clientDetails.ref}.pdf`,
          function (err, url) {
            shortenUrl = url;

            let sms_content = result.data.data.sms_body.replace(
              "#pdfurl#",
              shortenUrl
            );

            let data = {
              prescription_id: clientDetails.id,
              patientId: clientDetails.patient.id,
              clinicId: localStorage.getItem("clinicId"),
              from_sender_id: "DoBiz",
              message: sms_content
            };
            PrescriptionService.sendPrescriptionSMS(data)
              .then((response) => {
                document.getElementById(idAttr).innerHTML = oldHtml;
                if (response.data.valid) {
                  setSubmitted({
                    valid: true,
                    message: "SMS has been sent successfully",
                  });
                } else {
                  setErrSubmitted({
                    valid: true,
                    message: response.data.message,
                  });
                }
                
              })
              .catch((e) => {
                console.log(e);
              });
          }
        );
      })
      .catch((e) => {
        console.log(e);
      });
  };

**Comment by harshdoshi999** [comment]
Can you please share Test URL of your PDF?

**Comment by GitanjaliCS** [comment]
PDF test url

https://139.59.17.239/pdf/client_prescription_pdf/32ad04e1-ff18-43d1-bd7e-dd9df96a4b53d521be4a-fd55-4f2e-8525-81001e847907.pdf

My code was working before..but from yesterday it is not working.

**Comment by harshdoshi999** [comment]
Its working fine. Try on runkit -- https://npm.runkit.com/node-url-shortener

Open above URL and copy-paste following and Run:
`
var shortUrl = require('node-url-shortener');

shortUrl.short('https://139.59.17.239:8081/pdf/client_prescription_pdf/32ad04e1-ff18-43d1-bd7e-dd9df96a4b53d521be4a-fd55-4f2e-8525-81001e847907.pdf', function(err, url){
    console.log(url);
});
`

**Comment by GitanjaliCS** [comment]
I have tried your code but its not working

  var shortUrl = require("node-url-shortener");

  shortUrl.short(
    "https://139.59.17.239:8081/pdf/client_prescription_pdf/32ad04e1-ff18-43d1-bd7e-dd9df96a4b53d521be4a-fd55-4f2e-8525-81001e847907.pdf",
    function (err, url) {
      console.log("==============>" + url);
    }
  );

No response log .

**Comment by GitanjaliCS** [comment]
Thank you it is working now. I have changed version by 2.0.0 earlier it was 1.2.2.

**Comment by harshitrastogi992** [comment]
Tried with new version, but it is giving undefined
