### ISSUE TITLE
Really doesn't work or what?

### ISSUE THREAD

**Issue by laps78** [harshdoshi999/node-url-shortener#9]
Hello!

It seems to me that the app doesn't do anything. See following screenshots:

1. My testing code file

![stdout results](https://github.com/user-attachments/assets/5412e275-78c7-432d-b909-01fe3db116a9)

2. STDOUT results

![testing code](https://github.com/user-attachments/assets/23afb687-226e-43cd-86e6-be46bfd51ccf)

PS: running source without *process.exit()* make process unceasing

**Comment by harshdoshi999** [comment]
Due to some reasons.. server was not available for some time.. its up and running.
